[package]
name = "u8-selector"
version = "0.1.0"
authors = ["xaoc"]

[dependencies]
log = "0.4"
futures = "^0.1"
bytes = "^0.4"
tokio-io = "^0.1"
tokio-serial = "0.8"
tokio = "^0.1"

[dev-dependencies]
pretty_env_logger = "0.2.3"

